openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/muhdwiar/WarehouseCapstoneProject/1.0.0
info:
  description: |
    This is a simple API of Warehouse App
    ### url: https://virtserver.swaggerhub.com/muhdwiar/WarehouseCapstoneProject/1.0.0
  version: "1.0.0"
  title: Warehouse App API
  
tags:
 
  - name: Auth
    description: Authentication
  - name: User
    description: User Controller
  - name: Lahan
    description: Lahan Controller
  - name: Gudang
    description: Gudang Controller
    
paths:
  ####################################
  #  LOGIN
  ####################################
  /login:
    post:
      tags:
        - Auth
      summary: login user
      parameters:
      - in: query
        name: role
        schema:
          type: string
          example: mitra/client 
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestLogin'
            example:
              email : "user@mail.com"
              password : "your password"
      responses:
        '200':
          description: Success Login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseLoginSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "login success",
                    data: {
                      token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzgzMjYxODAsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.AebFR-oQjUSOMez2ucDWkiMrS2eQIPmcYm5c71qZ_co",
                      nama: "Lala Tralala"
                    }
                  }
        '400':
          description: Fail Login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "login fail"
                  }
  /register:
    post:
      tags:
        - Auth
      summary: register user
      parameters:
      - in: query
        name: role
        schema:
          type: string
          example: mitra/client 
        required: true 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
            example:
              name: "new user"
              address: "Bali"
              no_handphone: "085712344321"
              email : "user@mail.com"
              password : "your_password"
              role: mitra
              ktp_mitra: "ktp_mitra.jpg"
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              name: "new user"
              address: "Bali"
              no_handphone: "085712344321"
              email : "user@mail.com"
              password : "your_password"
              role: client
      responses:
        '200':
          description: Success Register User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "register success",
                  }
        '400':
          description: Fail Register User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "register fail"
                  }         
 
  ####################################
  #  USER
  ####################################    
  /admin/verify:
    get:
      tags:
        - User
      summary: see all request mitra
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Success Get All Unverified Mitra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseListMitra'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get all data unverified mitra"
                    data: 
                        [
                          {
                            name: "fatmawati warehouse",
                          },
                          {
                            name: "lembang warehouse",
                          } 
                        ]                    
        '400':
          description: Fail Get All Unverified Mitra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get all data unverified mitra fail"
                  }    
  /admin/verify/{id}:  
    put:
      tags:
        - User
      summary: verify mitra
      security:
        - JWTAuth: []
      parameters:
        - name: id
          description: id of mitra
          in: path
          schema:
            type: integer
            example: 1
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/verifyRequest'
            examples:
              verified:
                summary: example of verified
                value:
                  verify: "yes"
              rejected:
                summary: example of rejected
                value:
                  verify: "no"
      responses:
        '200':
          description: Success Verify
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "verification success"
                  }
        '400':
          description: Fail Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "verification fail"
                  }
  /admin/mitra:
    get:
      tags:
        - User
      summary: see all verified mitra
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Get All Verified Mitra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseListMitra'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get all verified mitra success"
                    data: 
                        [
                           {
                            name: "fatmawati warehouse",
                          },
                          {
                            name: "lembang warehouse",
                          } 
                        ]                          
        '400':
          description: Fail Get All Verified Mitra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get all data mitra fail"
                  }
  /admin/mitra/{id}:
    get:
      tags:
        - User
      summary: see detail mitra profile
      security:
        - JWTAuth: []
      parameters:
        - name: id
          description: id of mitra
          in: path
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Get Detail Verified Mitra
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseDetailMitra'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get detail mitra success"
                    data: {
                          id: 1,
                          name: "new user",
                          address: "Bali",
                          no_handphone: "085712344321",
                          email : "user@mail.com",
                          file_ktp : "user_ktp.jpg",
                          profile_photo: "profile_photo.jpg"  ,
                          gudang_name: "fatmawati warehouse",
                          gudang_location: "bandung"
                        }                 
        '400':
          description: Fail Get All User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get detail mitra fail"
                    
                  }
    delete:
      tags:
        - User
      summary: delete verified mitra
      security:
        - JWTAuth: []
      parameters:
        - name: id
          description: id of verified mitra
          in: path
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Success Delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "success delete"
                  }
        '400':
          description: Fail Delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "failed delete"
                  }
  
  
  ####################################
  #  LAHAN
  #################################### 
  /lahan:
    post:
      tags:
        - Lahan
      summary: add gudang
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/requestLahan'
          application/json:
            schema:
              $ref: '#/components/schemas/requestLahan'
            example:
              nama: "fatmawati gudang"
              luas: "42m"
              panjang: "7m"
              lebar : "6m"
              harga : 1200000
              tentang_gudang: "berbentuk ruangan bisa dikunci"
              fasilitas: "cctv"
              barang_yang_tidak_diizinkan: "benda tajam"
              photo_lahan: "photo_lahan.jpg"
      responses:
        '200':
          description: Success add lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "success add lahan",
                  }
        '400':
          description: Fail Add Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "failed add lahan"
                  }
  /lahan/{id}:
    get:
      tags:
        - Lahan
      summary: see detail lahan
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Get Detail Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseDetailLahan'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get detail lahan success"
                    data:  
                        luas: "200m"
                        address: "bandung"                  
                        barang_yang_tidak_diizinkan: "benda tajam"
                        lain_lain: ""
                        photo_lahan: "photo_lahan.jpg"
                        harga: 1200000
                        nama_penyewa: "dian"
                        tanggal_mulai_sewa: "2022-01-01"
                        tanggal_akhir_sewa: "2022_02-01"
                        photo_product: "photo_product.jpg"
                        alamat_client: "alamat_clien"                   
        '400':
          description: Fail Get All Gudang
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get detail lahan fail"
                  }
    put:
      tags:
        - Lahan
      summary: update lahan
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/requestLahan'
          application/json:
            schema:
              $ref: '#/components/schemas/requestLahan'
            example:
              nama: "fatmawati gudang"
              luas: "42m"
              panjang: "7m"
              lebar : "6m"
              harga : 1200000
              tentang_gudang: "berbentuk ruangan bisa dikunci"
              fasilitas: "cctv"
              barang_yang_tidak_diizinkan: "benda tajam"
              photo_lahan: "photo_lahan.jpg"
      responses:
        '200':
          description: Success update lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "success update lahan",
                  }
        '400':
          description: Fail Update Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "failed update lahan"
                  }
    delete:
      tags:
        - Lahan
      summary: delete lahan
      security:
        - JWTAuth: []
      parameters:
        - name: id
          description: id_lahan
          in: path
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Success Delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "success delete "
                  }
        '400':
          description: Fail Delete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "failed delete"
                  }
  /myfavorite:
    get:
      tags:
        - Lahan
      summary: see my favorite lahan
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Get My Favorite Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseAllGudang'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get my favorite lahan success"
                    data: 
                        [
                           {
                            photo_gudang: "photo_gudang.jpg",
                            name: "fatmawati warehouse 300m",
                            harga: 1200000
                          },
                          {
                            photo_gudang: "photo_gudang.jpg",
                            name: "fatmawati warehouse 100m",
                            harga: 1000000
                          } 
                        ]                          
        '400':
          description: Fail Get My Favorite Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get my favorite lahan fail"
                  }

  ####################################
  #  GUDANG
  ####################################
  /gudang:
    get:
      tags:
        - Gudang
      summary: see all gudang
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Get All Gudang
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseAllGudang'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get all gudang success"
                    data: 
                        [
                           {
                            photo_gudang: "photo_gudang.jpg",
                            name: "fatmawati warehouse",
                            harga: 1200000
                          },
                          {
                            photo_gudang: "photo_gudang.jpg",
                            name: "lembang warehouse",
                            harga: 1000000
                          } 
                        ]                          
        '400':
          description: Fail Get All Gudang
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get all data mitra fail"
                  }
  /mygudang:
    get:
      tags:
        - Gudang
      summary: see my list lahan
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Get List Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseAllGudang'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get list lahan success"
                    data: 
                        [
                           {
                            photo_gudang: "photo_gudang.jpg",
                            name: "fatmawati warehouse 300m",
                            harga: 1200000
                          },
                          {
                            photo_gudang: "photo_gudang.jpg",
                            name: "fatmawati warehouse 100m",
                            harga: 1000000
                          } 
                        ]                          
        '400':
          description: Fail Get List Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get list lahan fail"
                  }
  /myroom:
    get:
      tags:
        - Gudang
      summary: get my room
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Get My Room
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseMyRoom'
            multipart/form-data:
              schema:
                $ref: '#/components/schemas/responseMyRoom'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get my room success"
                    data: 
                        [
                           {
                            photo_gudang: "photo_gudang.jpg",
                            gudang_name: "fatmawati warehouse",
                            luas: "200m",
                            address: "jl. kemerdekaan",
                            lahan_name: "fatmawati warehouse 100m",
                            tanggal_mulai_sewa: "2022-01-01",
                            tanggal_akhir_sewa: "2022-02-01",
                            product_name: "kulkas"
                          },
                          {
                            photo_gudang: "photo_gudang.jpg",
                            gudang_name: "fatmawati warehouse",
                            luas: "200m",
                            address: "jl. kemerdekaan",
                            lahan_name: "fatmawati warehouse 100m",
                            tanggal_mulai_sewa: "2022-01-01",
                            tanggal_akhir_sewa: "2022-02-01",
                            product_name: "motor"
                          } 
                        ] 
        '400':
          description: Fail Get My Room
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "get my room fail"
                  }

  ####################################
  #  CHECKOUT
  ####################################
  /checkout:
    post:
      tags:
        - Checkout
      summary:  checkout lahan
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/requestCheckoutLahan'
          application/json:
            schema:
              $ref: '#/components/schemas/requestCheckoutLahan'
            example:
              photo_lahan: "photo_lahan.jpg"
              lahan_name: "fatmawati gudang"
              harga : 1200000
              mulai_sewa: "2022-01-01"
              akhir_sewa: "2022-02-01"
              product_name: "kulkas"
              address: "jl. kemerdekaan"
              pickup_point: "masjid agung"
              ongkos_kirim: 30000
      responses:
        '200':
          description: Success checkout lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSuccess'
              examples:
                response1:
                  description: response success
                  value: {
                    status: "success",
                    message: "success checkout lahan",
                  }
        '400':
          description: Fail Checkout Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "failed checkout lahan"
                  }
    get:
      tags:
        - Checkout
      summary: get checkout lahan
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Get Checkout Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/requestCheckoutLahan'
              examples:
                response1:
                  description: response success
                  value:
                    status: "success"
                    message: "get checkout lahan success"
                    data:
                        [
                           {
                            photo_lahan: "photo_lahan.jpg",
                            lahan_name: "fatmawati gudang",
                            harga : 1200000,
                            mulai_sewa: "2022-01-01",
                            akhir_sewa: "2022-02-01",
                            product_name: "kulkas",
                            address: "jl. kemerdekaan",
                            pickup_point: "masjid agung",
                            ongkos_kirim: 30000,
                          },
                          {
                            photo_lahan: "photo_lahan.jpg",
                            lahan_name: "fatmawati gudang",
                            harga : 1200000,
                            mulai_sewa: "2022-01-01",
                            akhir_sewa: "2022-02-01",
                            product_name: "kulkas",
                            address: "jl. kemerdekaan",
                            pickup_point: "masjid agung",
                            ongkos_kirim: 30000,
                          } 
                        ]
        '400':
          description: Fail Get Checkout Lahan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseFail'
              examples:
                response1:
                  description: response fail
                  value: {
                    status: "failed",
                    message: "failed get checkout lahan"
                  }



####################################
  #  COMPONENTS
####################################
components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "use Token"

####################################
  #  SCHEMA
####################################
  schemas:

    User:
      type: object
      properties:
        id: 
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
        no_handphone:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum:
            - admin
            - client
            - mitra
        ktp_mitra: 
          type: string
    
    requestLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    requestLahan:
      type: object
      properties:
        nama:
          type: string
        luas:
          type: string
        panjang:
          type: string
        lebar:
          type: string
        harga:
          type: integer
        tentang_gudang:
          type: string
        fasilitas:
          type: string
        barang_yang_tidak_diizinkan:
          type: string
        photo_lahan:
          type: string
      
    requestCheckoutLahan:
      type: object
      properties:
        photo_lahan:
          type: string
        lahan_name:
          type: string
        harga:
          type: integer
        mulai_sewa:
          type: string
        akhir_sewa:
          type: integer
        product_photo:
          type: string
        product_name:
          type: string
        address:
          type: string
        pickup_point:
          type: string
        ongkos_kirim:
          type: integer
          
    responseLoginSuccess:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        },
        "data":{
          type: object,
          properties: {
            "token":{
              type: string},
            "name":{
              type: string}
          }
        }
      }
      
    verifyRequest:
      type: object
      properties:
        verify:
          type: string

    responseDetailMitra:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        },
        "data": {
        type: object,
        items: {
          type: object,
          properties: {
            "id": { 
              type: integer},
            "name":{ 
              type: string},
            "address":{ 
              type: string},
            "email":{ 
              type: string},
            "no_handphone":{ 
              type: string},
            "file_ktp":{ 
              type: string},
            "profile_photo":{
              type: string},
            "gudang_name":{
              type: string},
            "gudang_location":{
              type: string},
            }
          }
        }
      }
       
    responseListMitra:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        },
        "data": {
        type: array,
        items: {
          type: object,
          properties: {
            "name":{ 
              type: string},
            }
          }
        }
      }

    responseAllGudang:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        },
        "data": {
        type: array,
        items: {
          type: object,
          properties: {
            "photo_gudang":{ 
              type: string},
            "name":{ 
              type: string},
            "harga":{ 
              type: integer},
            }
          }
        }
      }

    responseMyRoom:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        },
        "data": {
        type: array,
        items: {
          type: object,
          properties: {
            "photo_gudang":{ 
              type: string},
            "gudang_name":{ 
              type: string},
            "luas":{ 
              type: integer},
            "address":{ 
              type: string},
            "lahan_name":{ 
              type: string},
            "tanggal_mulai_sewa":{ 
              type: string},
            "tanggal_akhir_sewa":{ 
              type: string},
            "product_name":{ 
              type: string},
            }
          }
        }
      }

    responseDetailLahan:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        },
        "data": {
        type: object,
        properties: {
          "luas":{ 
            type: string},
          "address":{ 
            type: string},
          "barang_yang_tidak_diizinkan":{ 
            type: string},
          "lain_lain":{ 
            type: string},
          "photo_lahan":{ 
            type: string},
          "harga":{ 
            type: integer},
          "nama_penyewa":{ 
            type: string},
          "tanggal_mulai_sewa":{ 
            type: string},
          "tanggal_akhir_sewa":{ 
            type: string},
          "photo_product":{ 
            type: string},
          "alamat_clien":{ 
            type: string},
          }
        }
      }

      
    responseSuccess:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        }
      }
    
    responseFail:
      type: object
      properties: {
        "status": {
          type: string
        },
        "message": {
          type: string
        }
      }